import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class ListView {
    private JPanel root;
    private JList list1;
    private JButton addItemButton;
    private JButton removeItemButton;

    DefaultListModel<String> list;

    public static void main(String[] args) {
        JFrame frame = new JFrame("ListView");
        frame.setContentPane(new ListView().root);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public ListView() {
        list  = new DefaultListModel<String>();
        list.addElement("First");

        addItemButton.addActionListener(e -> {
            list.addElement("item");
        });

        removeItemButton.addActionListener(e -> {
            list.remove(0);
        });

        list1.setModel(list);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridBagLayout());
        list1 = new JList();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        root.add(list1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        root.add(spacer1, gbc);
        addItemButton = new JButton();
        addItemButton.setText("Add Item");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        root.add(addItemButton, gbc);
        removeItemButton = new JButton();
        removeItemButton.setText("Remove Item");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        root.add(removeItemButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }
}
