# File: Makefile
# Class: CS 470                    # Instructor: Dr. Deborah Hwang
# Assignment:  Shell Project       # Date assigned: 1/24/2018
# Programmer: Kunal Mukherjee      # Date completed: 2/7/2018

shell:	shell.cpp
	clang++ shell.cpp -o shell -Wall -g 
