import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;

public class MainForm {

    // GUI Objects

    private JPanel rootPnl;
    private JLabel countLbl;
    private JButton upButton;
    private JButton downButton;
    private JLabel yLabel;
    private JLabel xLabel;
    private MyPanel myView;
    private MyPanel view1;
    private MyPanel myPanel1;
    private JPanel custom;

    // Model Object

    private int count;

    public static void main(String[] args) {
        JFrame frame = new JFrame("MainForm");
        frame.setContentPane(new MainForm().rootPnl);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public MainForm() {
        count = 10;
        myView.setPreferredSize(new Dimension(100, 100));
        update();

        upButton.addActionListener(evt -> {
            count++;
            update();
        });
        downButton.addActionListener(evt -> {
            count--;
            update();
        });

        rootPnl.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent e) {
                xLabel.setText("X:" + e.getX());
                yLabel.setText("Y:" + e.getY());
            }
        });

    }

    // Updates the displayed data
    private void update() {
        countLbl.setText(Integer.toString(count));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPnl = new JPanel();
        rootPnl.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Count:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        rootPnl.add(label1, gbc);
        countLbl = new JLabel();
        countLbl.setText("0");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        rootPnl.add(countLbl, gbc);
        upButton = new JButton();
        upButton.setText("Up");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rootPnl.add(upButton, gbc);
        downButton = new JButton();
        downButton.setText("Down");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rootPnl.add(downButton, gbc);
        xLabel = new JLabel();
        xLabel.setText("X:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        rootPnl.add(xLabel, gbc);
        yLabel = new JLabel();
        yLabel.setText("Y:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        rootPnl.add(yLabel, gbc);
        myView = new MyPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        rootPnl.add(myView, gbc);
        view1 = new MyPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        rootPnl.add(view1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPnl;
    }
}
