# File: Makefile
# Class: CS 470                                      # Instructor: Dr. Deborah Hwang
# Assignment:  Thread Synchronization Project       # Date assigned: 2/9/2018
# Programmer: Kunal Mukherjee                        # Date completed: 2/18/2018

shell:	thread.cpp
	g++ -o thread thread.cpp -lpthread
